-
  name: set syslog server
  hosts: all
  tasks:

  - name: set syslog server ios
    cisco.ios.ios_command:
      commands:
      - configure terminal
      - command: logging host 1.1.1.1
    ignore_errors: yes

  - name: save ios config
    cisco.ios.ios_config:
      save_when: always
    ignore_errors: yes

  - name: set syslog server nxos
    cisco.nxos.nxos_command:
      commands:
      - configure
      - command: logging server 2.2.2.2
    ignore_errors: yes

  - name: save nxos config
    cisco.nxos.nxos_config:
      save_when: always
    ignore_errors: yes